global:
  scrape_interval: 15s

scrape_configs:
  # Scrape prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "preprocessor"
    static_configs:
      - targets: ["preprocessor:9100"]

  - job_name: "feature_extractor"
    static_configs:
      - targets: ["feature_extractor:9100"]

  - job_name: "classifier"
    static_configs:
      - targets: ["classifier:9100"]

  - job_name: "provenance"
    static_configs:
      - targets: ["provenance:9100"]
